src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get( '/', [
  'as'   => 'home',
  'uses' => 'HomeController@index'
] );

Route::resource( 'sessions', 'SessionsController' );
Route::get( 'logout', [ 'as' => 'logout', 'uses' => 'SessionsController@destroy' ] );

Route::group( array( 'before' => 'csrf|auth' ), function ()
{

  Route::get( 'shipments/{typeAndYear}/{fileNumber}', 'ShipmentsController@showByFileNumber' )
       ->where( 'typeAndYear', '(im|ex|IM|EX)\-[0-9]{2}' )
       ->where( 'fileNumber', '[0-9]{3}' );

  Route::resource( 'shipments', 'ShipmentsController' );
  Route::resource( 'shipments.items', 'ShipmentsItemsController' );
  Route::resource( 'shipments.tasks', 'ShipmentsTasksController' );
  Route::resource( 'shipments.documents', 'ShipmentsDocumentsController' );
  Route::resource( 'shipments.costsheets', 'ShipmentsCostsheetsController' );
  Route::resource( 'shipments.invoices', 'ShipmentsInvoicesController' );
  Route::resource( 'shipments.invoices.items', 'ShipmentsInvoicesItemsController' );

  Route::resource( 'documents', 'DocumentsController' );
  Route::resource( 'ports', 'PortsController' );
  Route::resource( 'vessels', 'VesselsController' );

  Route::resource( 'customers', 'CustomersController' );


  Route::resource( 'users', 'UsersController' );
  Route::resource( 'groups', 'GroupsController' );

  Route::get( 'dashboard', [ 'as' => 'dashboard', function () { return View::make( 'dashboard.index' ); } ] );

  Route::get( 'hrm', function () { return Redirect::route('users.index'); } );
  Route::get( 'crm', function () { return Redirect::route('customers.index'); } );
  Route::get( 'rm', function () { return Redirect::route('documents.index'); } );

  Route::get( 'search', function () { return Redirect::to( 'shipments/' . Input::get('q') ); } );
  Route::get( 'endpoints', function () { return View::make( 'static.endpoints' ); } );
  Route::get( 'help', function () { return View::make( 'static.help' ); } );

} );


Route::get( 'debug', function ()
{

  $shipmentId = 1;
  $invoiceId  = 89;
  Kint::dump(
    JTS\Entities\Shipments\Shipment::findOrFail( $shipmentId )
                                   ->invoices()->findOrFail( $invoiceId )
                                   ->update( [ ] )
  );
  die();
} );

src/app/controllers/ShipmentsController.php
<?php

use JTS\Entities\Customers\CustomerRepositoryInterface;
use JTS\Entities\Resources\Ports\PortRepositoryInterface;
use JTS\Entities\Resources\Vessels\VesselRepositoryInterface;
use JTS\Entities\Shipments\ShipmentRepositoryInterface;
use JTS\Core\Exceptions\ValidationException;

class ShipmentsController extends \AbstractBaseController {

  /**
   * @var ShipmentRepositoryInterface
   */
  private $shipment;

  /**
   * @var \JTS\Entities\Customers\CustomerRepositoryInterface
   */
  private $customer;

  /**
   * @var \JTS\Entities\Resources\Ports\PortRepositoryInterface
   */
  private $port;

  /**
   * @var \VesselRepositoryInterface
   */
  private $vessel;

  /**
   * @param ShipmentRepositoryInterface                           $shipment
   * @param \JTS\Entities\Customers\CustomerRepositoryInterface   $customer
   * @param \JTS\Entities\Resources\Ports\PortRepositoryInterface $port
   * @param \VesselRepositoryInterface                            $vessel
   */
  public function __construct(ShipmentRepositoryInterface $shipment,
                              CustomerRepositoryInterface $customer,
                              PortRepositoryInterface $port,
                              VesselRepositoryInterface $vessel)
  {
    $this->shipment = $shipment;
    $this->customer = $customer;
    $this->port     = $port;
    $this->vessel = $vessel;
  }

  /**
   * Display a listing of shipments
   *
   * @return Response
   */
  public function index()
  {
    $shipments = $this->shipment->getAll();

    if ( Request::ajax() )
    {
      return $shipments;
    }

    return View::make( 'shipments.index', compact( 'shipments' ) );
  }

  /**
   * Show the form for creating a new shipment
   *
   * @return Response
   */
  public function create()
  {
    $shipment = $this->shipment->getNewDefault();

    return View::make( 'shipments.create', compact( 'shipment' ) );
  }

  /**
   * Store a newly created shipment in storage.
   *
   * @return Response
   */
  public function store()
  {
    try
    {
      $shipment = $this->shipment->create( Input::all() );
    }
    catch ( ValidationException $e )
    {
      return Redirect::back()
                     ->withErrors( $e->getValidator() )
                     ->withInput();
    }

    return Redirect::route( 'shipments.edit', [ $shipment->id ] );
  }

  /**
   * Display the specified shipment.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function show($id)
  {
    return Redirect::route( 'shipments.edit', [ $id ] );
  }

  /**
   * Display the specified shipment via qualified file number.
   *
   * @param $typeAndYear
   * @param $fileNumber
   *
   * @return Response
   */
  public function showByFileNumber($typeAndYear, $fileNumber)
  {
    $type       = strtolower( substr( $typeAndYear, 0, 2 ) ) === 'im' ? 'import' : 'export';
    $fileNumber = intval( $fileNumber );
    $year       = intval( substr( $typeAndYear, 3 ) ) + 2000;

    $shipment = $this->shipment->getByFileNumber( $type, $year, $fileNumber );

    return View::make( 'shipments.edit', compact( 'shipment', [ $shipment->id ] ) );
  }

  /**
   * Show the form for editing the specified shipment.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function edit($id)
  {
    $shipment     = $this->shipment->getById( $id );

    return View::make( 'shipments.edit', compact( 'shipment' ) );
  }

  /**
   * Update the specified shipment in storage.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function update($id)
  {
    try
    {
      $this->shipment->update( $id, Input::all() );
      $shipment = $this->shipment->getById($id);
      $shipment->users()->sync(Input::get('assigned_to'));
    }
    catch ( ValidationException $e )
    {
      return Redirect::back()->withErrors( $e->getValidator() )->withInput();
    }

    return Redirect::route( 'shipments.edit', $id )->with( 'success', trans( 'ui.updated' ) );
  }

  /**
   * Remove the specified shipment from storage.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function destroy($id)
  {
    $this->shipment->destroy( $id );

    return Redirect::route( 'shipments.index' );
  }

  /**
   * Restore the specified shipment from storage.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function restore($id)
  {
    $this->shipment->restore( $id );

    return Redirect::route( 'shipments.show', $id );
  }

}

src/app/views/shipments/items/_form.blade.php
<div class="form-group">
  {{ Form::label('name', trans('jts.name'), ['class' => 'col-md-2  control-label'] ) }}
  <div class="col-md-10">
    {{ Form::text('name', null, ['class' => 'form-control'] ) }}
    {{ $errors->first('name', '<span class="help-block">:message</span>') }}
  </div>
</div>

<div class="form-group">
  {{ Form::label('serial_number', trans('jts.serial_number'), ['class' => 'col-md-2  control-label'] ) }}
  <div class="col-md-10">
    {{ Form::text('serial_number', null, ['class' => 'form-control'] ) }}
    {{ $errors->first('serial_number', '<span class="help-block">:message</span>') }}
  </div>
</div>


<div class="form-group">
  {{ Form::label('description', trans('jts.description'), ['class' => 'col-md-2  control-label'] ) }}
  <div class="col-md-10">
    {{ Form::textarea('description', null, ['class' => 'form-control', 'rows' => 5] ) }}
    {{ $errors->first('description', '<span class="help-block">:message</span>') }}
  </div>
</div>

src/app/views/shipments/items/create.blade.php
@extends('layouts.default')

@section('sidebar')
  @include('shipments._edit_sidebar')
  @parent
@stop

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="well">

      {{ Form::open(['route' => ['shipments.items.store', $shipment->id], 'method' => 'post', 'class' => 'form-horizontal']) }}

        <fieldset>
          <legend>{{ trans('jts.creating_item', ['fileNumber' => $fileNumber]) }}</legend>

          @include('shipments.items._form')

          <div class="form-group">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div class="pull-right">
                {{ Form::submit(trans('ui.save'), ['class' => 'btn btn-primary']) }}
              </div>
            </div>
          </div>
        </fieldset>

      {{ Form::close() }}

    </div> <!-- .well -->
  </div> <!-- .col -->
</div> <!-- .row -->
@stop

src/app/views/shipments/items/edit.blade.php
@extends('layouts.default')

@section('sidebar')
  @include('shipments._edit_sidebar')
  @parent
@stop

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="well">

      {{ Form::model($item, ['route' => ['shipments.items.update', $shipment->id, $item->id], 'method' => 'put', 'class' => 'form-horizontal']) }}

        <fieldset>
          <legend>{{ trans('jts.editing_item', ['fileNumber' => $fileNumber]) }}</legend>

          @include('shipments.items._form')

          <div class="form-group">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="pull-right">
                  {{ Form::submit(trans('ui.update'), ['class' => 'btn btn-primary']) }}
                  {{ Form::button(trans('ui.undo_changes'), ['class' => 'btn btn-default', 'type' => 'reset']) }}
                </div>
                <div class="pull-left">
                  <a class="btn btn-danger" href="{{ route('shipments.items.destroy', [$shipment->id, $item->id] ) }}" data-method="delete">{{ trans('ui.delete') }}</a>
                </div>
            </div>
          </div>
        </fieldset>

      {{ Form::close() }}

    </div> <!-- .well -->
  </div> <!-- .col -->
</div> <!-- .row -->

@stop

src/app/views/shipments/items/index.blade.php
@extends('layouts.default')

@section('sidebar')
  @include('shipments._edit_sidebar')
@parent
@stop

@section('content')
<div class="row">
  <div class="col-md-12">

    <div class="panel panel-default">
      <div class="panel-heading clearfix">
        <strong class="panel-title">Items</strong>
        <div class="pull-right">
          <a class="btn btn-primary btn-sm" href="{{ route('shipments.items.create', $shipment->id) }}"><i class="glyphicon glyphicon-plus"></i>{{ trans('jts.new_item') }}</a>
        </div>
      </div>
      <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
          <tr>
            <th style="width:20%;">{{ trans('jts.name') }}</th>
            <th style="width:20%;">{{ trans('jts.serial_number') }}</th>
            <th style="width:60%;">{{ trans('jts.description') }}</th>
          </tr>
        </thead>
        <tbody>
            @foreach($items as $item)
              <tr>
                <td><a href="{{ route('shipments.items.edit', [$shipment->id, $item->id]) }}">{{ $item->present()->name }}</a></td>
                <td>{{ $item->serial_number }}</td>
                <td>{{ $item->present()->description }}</td>
              </tr>
            @endforeach
        </tbody>
      </table>

      <div class="panel-footer clearfix">
        <div class="pull-right">
          {{ $items->appends(Input::except('page'))->links() }}
        </div>
      </div>
    </div>

  </div>
</div>
@stop

src/app/views/shipments/items/show.blade.php
{{{ $item }}}