src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get( '/', [
  'as'   => 'home',
  'uses' => 'HomeController@index'
] );

Route::resource( 'sessions', 'SessionsController' );
Route::get( 'logout', [ 'as' => 'logout', 'uses' => 'SessionsController@destroy' ] );

Route::group( array( 'before' => 'csrf|auth' ), function ()
{

  Route::get( 'shipments/{typeAndYear}/{fileNumber}', 'ShipmentsController@showByFileNumber' )
       ->where( 'typeAndYear', '(im|ex|IM|EX)\-[0-9]{2}' )
       ->where( 'fileNumber', '[0-9]{3}' );

  Route::resource( 'shipments', 'ShipmentsController' );
  Route::resource( 'shipments.items', 'ShipmentsItemsController' );
  Route::resource( 'shipments.tasks', 'ShipmentsTasksController' );
  Route::resource( 'shipments.documents', 'ShipmentsDocumentsController' );
  Route::resource( 'shipments.costsheets', 'ShipmentsCostsheetsController' );
  Route::resource( 'shipments.invoices', 'ShipmentsInvoicesController' );
  Route::resource( 'shipments.invoices.items', 'ShipmentsInvoicesItemsController' );

  Route::resource( 'documents', 'DocumentsController' );
  Route::resource( 'ports', 'PortsController' );
  Route::resource( 'vessels', 'VesselsController' );

  Route::resource( 'customers', 'CustomersController' );


  Route::resource( 'users', 'UsersController' );
  Route::resource( 'groups', 'GroupsController' );

  Route::get( 'dashboard', [ 'as' => 'dashboard', function () { return View::make( 'dashboard.index' ); } ] );

  Route::get( 'hrm', function () { return Redirect::route('users.index'); } );
  Route::get( 'crm', function () { return Redirect::route('customers.index'); } );
  Route::get( 'rm', function () { return Redirect::route('documents.index'); } );

  Route::get( 'search', function () { return Redirect::to( 'shipments/' . Input::get('q') ); } );
  Route::get( 'endpoints', function () { return View::make( 'static.endpoints' ); } );
  Route::get( 'help', function () { return View::make( 'static.help' ); } );

} );


Route::get( 'debug', function ()
{

  $shipmentId = 1;
  $invoiceId  = 89;
  Kint::dump(
    JTS\Entities\Shipments\Shipment::findOrFail( $shipmentId )
                                   ->invoices()->findOrFail( $invoiceId )
                                   ->update( [ ] )
  );
  die();
} );

src/app/views/shipments/invoices/items/_index_sidebar.blade.php
<li><a href="{{ route('shipments.invoices.items.create', [$shipment->id, $invoice->id] ) }}"><i class="glyphicon glyphicon-plus"></i>{{ trans('jts.new_invoice_item') }}</a></li>

src/app/views/shipments/invoices/items/create.blade.php
@extends('layouts.default')

@section('content')

@stop

src/app/views/shipments/invoices/items/edit.blade.php
@extends('layouts.default')

@section('content')
{{ $item }}
@stop

src/app/views/shipments/invoices/items/index.blade.php
@extends('layouts.default')

@section('sidebar')
  @include('shipments_invoices_items._index_sidebar')
@parent
@stop

@section('content')
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-bordered table-hover table-condensed">
      <thead>
        <tr>
          <th style="width:30%;">{{ trans('jts.description') }}</th>
          <th>{{ trans('jts.amount') }}</th>
        </tr>
      </thead>
      <tbody>
          @foreach($items as $item)
            <tr>
              <td>{{ $item->present()->description }}</td>
              <td>{{ $item->amount }}</td>
            </tr>
          @endforeach
      </tbody>
    </table>

    <div class="pull-right">
      {{ $items->appends(Input::except('page'))->links() }}
    </div>

  </div>
</div>
@stop

src/app/views/shipments/invoices/items/show.blade.php
{{{ $item }}}