src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get( '/', [
  'as'   => 'home',
  'uses' => 'HomeController@index'
] );

Route::resource( 'sessions', 'SessionsController' );
Route::get( 'logout', [ 'as' => 'logout', 'uses' => 'SessionsController@destroy' ] );

Route::group( array( 'before' => 'csrf|auth' ), function ()
{

  Route::get( 'shipments/{typeAndYear}/{fileNumber}', 'ShipmentsController@showByFileNumber' )
       ->where( 'typeAndYear', '(im|ex|IM|EX)\-[0-9]{2}' )
       ->where( 'fileNumber', '[0-9]{3}' );

  Route::resource( 'shipments', 'ShipmentsController' );
  Route::resource( 'shipments.items', 'ShipmentsItemsController' );
  Route::resource( 'shipments.tasks', 'ShipmentsTasksController' );
  Route::resource( 'shipments.documents', 'ShipmentsDocumentsController' );
  Route::resource( 'shipments.costsheets', 'ShipmentsCostsheetsController' );
  Route::resource( 'shipments.invoices', 'ShipmentsInvoicesController' );
  Route::resource( 'shipments.invoices.items', 'ShipmentsInvoicesItemsController' );

  Route::resource( 'documents', 'DocumentsController' );
  Route::resource( 'ports', 'PortsController' );
  Route::resource( 'vessels', 'VesselsController' );

  Route::resource( 'customers', 'CustomersController' );


  Route::resource( 'users', 'UsersController' );
  Route::resource( 'groups', 'GroupsController' );

  Route::get( 'dashboard', [ 'as' => 'dashboard', function () { return View::make( 'dashboard.index' ); } ] );

  Route::get( 'hrm', function () { return Redirect::route('users.index'); } );
  Route::get( 'crm', function () { return Redirect::route('customers.index'); } );
  Route::get( 'rm', function () { return Redirect::route('documents.index'); } );

  Route::get( 'search', function () { return Redirect::to( 'shipments/' . Input::get('q') ); } );
  Route::get( 'endpoints', function () { return View::make( 'static.endpoints' ); } );
  Route::get( 'help', function () { return View::make( 'static.help' ); } );

} );


Route::get( 'debug', function ()
{

  $shipmentId = 1;
  $invoiceId  = 89;
  Kint::dump(
    JTS\Entities\Shipments\Shipment::findOrFail( $shipmentId )
                                   ->invoices()->findOrFail( $invoiceId )
                                   ->update( [ ] )
  );
  die();
} );

src/app/controllers/ShipmentsController.php
<?php

use JTS\Entities\Customers\CustomerRepositoryInterface;
use JTS\Entities\Resources\Ports\PortRepositoryInterface;
use JTS\Entities\Resources\Vessels\VesselRepositoryInterface;
use JTS\Entities\Shipments\ShipmentRepositoryInterface;
use JTS\Core\Exceptions\ValidationException;

class ShipmentsController extends \AbstractBaseController {

  /**
   * @var ShipmentRepositoryInterface
   */
  private $shipment;

  /**
   * @var \JTS\Entities\Customers\CustomerRepositoryInterface
   */
  private $customer;

  /**
   * @var \JTS\Entities\Resources\Ports\PortRepositoryInterface
   */
  private $port;

  /**
   * @var \VesselRepositoryInterface
   */
  private $vessel;

  /**
   * @param ShipmentRepositoryInterface                           $shipment
   * @param \JTS\Entities\Customers\CustomerRepositoryInterface   $customer
   * @param \JTS\Entities\Resources\Ports\PortRepositoryInterface $port
   * @param \VesselRepositoryInterface                            $vessel
   */
  public function __construct(ShipmentRepositoryInterface $shipment,
                              CustomerRepositoryInterface $customer,
                              PortRepositoryInterface $port,
                              VesselRepositoryInterface $vessel)
  {
    $this->shipment = $shipment;
    $this->customer = $customer;
    $this->port     = $port;
    $this->vessel = $vessel;
  }

  /**
   * Display a listing of shipments
   *
   * @return Response
   */
  public function index()
  {
    $shipments = $this->shipment->getAll();

    if ( Request::ajax() )
    {
      return $shipments;
    }

    return View::make( 'shipments.index', compact( 'shipments' ) );
  }

  /**
   * Show the form for creating a new shipment
   *
   * @return Response
   */
  public function create()
  {
    $shipment = $this->shipment->getNewDefault();

    return View::make( 'shipments.create', compact( 'shipment' ) );
  }

  /**
   * Store a newly created shipment in storage.
   *
   * @return Response
   */
  public function store()
  {
    try
    {
      $shipment = $this->shipment->create( Input::all() );
    }
    catch ( ValidationException $e )
    {
      return Redirect::back()
                     ->withErrors( $e->getValidator() )
                     ->withInput();
    }

    return Redirect::route( 'shipments.edit', [ $shipment->id ] );
  }

  /**
   * Display the specified shipment.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function show($id)
  {
    return Redirect::route( 'shipments.edit', [ $id ] );
  }

  /**
   * Display the specified shipment via qualified file number.
   *
   * @param $typeAndYear
   * @param $fileNumber
   *
   * @return Response
   */
  public function showByFileNumber($typeAndYear, $fileNumber)
  {
    $type       = strtolower( substr( $typeAndYear, 0, 2 ) ) === 'im' ? 'import' : 'export';
    $fileNumber = intval( $fileNumber );
    $year       = intval( substr( $typeAndYear, 3 ) ) + 2000;

    $shipment = $this->shipment->getByFileNumber( $type, $year, $fileNumber );

    return View::make( 'shipments.edit', compact( 'shipment', [ $shipment->id ] ) );
  }

  /**
   * Show the form for editing the specified shipment.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function edit($id)
  {
    $shipment     = $this->shipment->getById( $id );

    return View::make( 'shipments.edit', compact( 'shipment' ) );
  }

  /**
   * Update the specified shipment in storage.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function update($id)
  {
    try
    {
      $this->shipment->update( $id, Input::all() );
      $shipment = $this->shipment->getById($id);
      $shipment->users()->sync(Input::get('assigned_to'));
    }
    catch ( ValidationException $e )
    {
      return Redirect::back()->withErrors( $e->getValidator() )->withInput();
    }

    return Redirect::route( 'shipments.edit', $id )->with( 'success', trans( 'ui.updated' ) );
  }

  /**
   * Remove the specified shipment from storage.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function destroy($id)
  {
    $this->shipment->destroy( $id );

    return Redirect::route( 'shipments.index' );
  }

  /**
   * Restore the specified shipment from storage.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function restore($id)
  {
    $this->shipment->restore( $id );

    return Redirect::route( 'shipments.show', $id );
  }

}

src/app/views/shipments/invoices/_form.blade.php
<div class="form-group">
  {{ Form::label('invoice_number', trans('jts.invoice_number'), ['class' => 'col-md-2  control-label'] ) }}
  <div class="col-md-10">
    {{ Form::text('invoice_number', null, ['class' => 'form-control'] ) }}
    {{ $errors->first('invoice_number', '<span class="help-block">:message</span>') }}
  </div>
</div>


<div class="form-group">
  {{ Form::label('description', trans('jts.description'), ['class' => 'col-md-2  control-label'] ) }}
  <div class="col-md-10">
    {{ Form::textarea('description', null, ['class' => 'form-control', 'rows' => 5] ) }}
    {{ $errors->first('description', '<span class="help-block">:message</span>') }}
  </div>
</div>

src/app/views/shipments/invoices/create.blade.php
@extends('layouts.default')

@section('sidebar')
  @include('shipments._edit_sidebar')
  @parent
@stop

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="well">

      {{ Form::model($invoice, ['route' => ['shipments.invoices.store', $shipment->id], 'method' => 'post', 'class' => 'form-horizontal']) }}

        <fieldset>
          <legend>{{ trans('jts.creating_item', ['fileNumber' => $fileNumber]) }}</legend>

          @include('shipments.invoices._form')

          <div class="form-group">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div class="pull-right">
                {{ Form::submit(trans('ui.save'), ['class' => 'btn btn-primary']) }}
              </div>
            </div>
          </div>
        </fieldset>

      {{ Form::close() }}

    </div> <!-- .well -->
  </div> <!-- .col -->
</div> <!-- .row -->
@stop

src/app/views/shipments/invoices/edit.blade.php
@extends('layouts.default')

@section('sidebar')
  @include('shipments._edit_sidebar')
  @parent
@stop

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="well">

      {{ Form::model($invoice, ['route' => ['shipments.invoices.update', $shipment->id, $invoice->id], 'method' => 'put', 'class' => 'form-horizontal']) }}

        <fieldset>
          <legend>{{ trans('jts.editing_item', ['fileNumber' => $fileNumber]) }}</legend>

          @include('shipments.invoices._form')

          <div class="form-group">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="pull-right">
                  {{ Form::submit(trans('ui.update'), ['class' => 'btn btn-primary']) }}
                  {{ Form::button(trans('ui.undo_changes'), ['class' => 'btn btn-default', 'type' => 'reset']) }}
                </div>
                <div class="pull-left">
                  <a class="btn btn-danger" href="{{ route('shipments.invoices.destroy', [$shipment->id, $invoice->id] ) }}" data-method="delete">{{ trans('ui.delete') }}</a>
                </div>
            </div>
          </div>
        </fieldset>

      {{ Form::close() }}

    </div> <!-- .well -->
  </div> <!-- .col -->
</div> <!-- .row -->

@stop

src/app/views/shipments/invoices/index.blade.php
@extends('layouts.default')

@section('sidebar')
  @include('shipments._edit_sidebar')
@parent
@stop

@section('content')
<div class="row">
  <div class="col-md-12">

    <div class="panel panel-default">
      <div class="panel-heading clearfix">
        <strong class="panel-title">Invoices</strong>
        <div class="pull-right">
          <a class="btn btn-primary btn-sm" href="{{ route('shipments.invoices.create', $shipment->id) }}"><i class="glyphicon glyphicon-plus"></i>{{ trans('jts.new_invoice') }}</a>
        </div>
      </div>

      <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
          <tr>
            <th width="10%">{{ trans('jts.invoice_number') }}</th>
            <th>{{ trans('jts.description') }}</th>
            <th width="20%">{{ trans('ui.action') }}</th>
          </tr>
        </thead>
        <tbody>
            @foreach($invoices as $invoice)
              <tr>
                <td><a href="{{ route('shipments.invoices.edit', [$shipment->id, $invoice->id]) }}">{{ $invoice->present()->invoiceNumber }}</a></td>
                <td>{{ $invoice->present()->description }}</td>
                <td><a href="{{ route('shipments.invoices.show', [$shipment->id, $invoice->id]) }}?pdf=1" target="_window"><i class="glyphicon glyphicon-print"></i>Generate PDF</a></td>
              </tr>
            @endforeach
        </tbody>
      </table>

      <div class="panel-footer clearfix">
        <div class="pull-right">
          {{ $invoices->appends(Input::except('page'))->links() }}
        </div>
      </div>
    </div>

  </div>
</div>
@stop

src/app/views/shipments/invoices/pdf.blade.php
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title>Print Friendly Invoice</title>
  <link rel="stylesheet" href="{{ asset('assets/bower/bootstrap/dist/css/bootstrap.min.css') }}">
  <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:100' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono' rel='stylesheet' type='text/css'>
  <style>
  /*******************************************************************
  This chunk is to fix Bootstrap so that the Markdown output looks good
  *******************************************************************/
  xmp, textarea {
    display: none;
  }

  h1,h2,h3,h4 {
    margin: 15px 0;
  }

  pre {
    margin: 20px 0;
  }

  img {
    margin: 10px 0;
  }


  /*******************************************************************
  This chunk is for Google's Code Prettify:
  http://google-code-prettify.googlecode.com
  *******************************************************************/
  /* Pretty printing styles. Used with prettify.js. */
  /* SPAN elements with the classes below are added by prettyprint. */
  .pln { color: #000 }  /* plain text */

  @media screen {
    .str { color: #080 }  /* string content */
    .kwd { color: #008 }  /* a keyword */
    .com { color: #800 }  /* a comment */
    .typ { color: #606 }  /* a type name */
    .lit { color: #066 }  /* a literal value */
    /* punctuation, lisp open bracket, lisp close bracket */
    .pun, .opn, .clo { color: #660 }
    .tag { color: #008 }  /* a markup tag name */
    .atn { color: #606 }  /* a markup attribute name */
    .atv { color: #080 }  /* a markup attribute value */
    .dec, .var { color: #606 }  /* a declaration; a variable name */
    .fun { color: red }  /* a function name */
  }

  /* Use higher contrast and text-weight for printable form. */
  @media print, projection {
    .str { color: #060 }
    .kwd { color: #006; font-weight: bold }
    .com { color: #600; font-style: italic }
    .typ { color: #404; font-weight: bold }
    .lit { color: #044 }
    .pun, .opn, .clo { color: #440 }
    .tag { color: #006; font-weight: bold }
    .atn { color: #404 }
    .atv { color: #060 }
  }

  /* Put a border around prettyprinted code snippets. */
  pre.prettyprint { padding: 2px; border: 1px solid #888 }

  /* Specify class=linenums on a pre to get line numbering */
  ol.linenums { margin-top: 0; margin-bottom: 0 } /* IE indents via margin-left */
  li.L0,
  li.L1,
  li.L2,
  li.L3,
  li.L5,
  li.L6,
  li.L7,
  li.L8 { list-style-type: none }
  /* Alternate shading for lines */
  li.L1,
  li.L3,
  li.L5,
  li.L7,
  li.L9 { background: #eee }


  html{font-size:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;}
  a:focus{outline:thin dotted #333;outline:5px auto -webkit-focus-ring-color;outline-offset:-2px;}
  a:hover,a:active{outline:0;}
  sub,sup{position:relative;font-size:75%;line-height:0;vertical-align:baseline;}
  sup{top:-0.5em;}
  sub{bottom:-0.25em;}
  img{max-width:100%;width:auto\9;height:auto;vertical-align:middle;border:0;-ms-interpolation-mode:bicubic;}
  button,input,select,textarea{margin:0;font-size:100%;vertical-align:middle;}
  button,input{*overflow:visible;line-height:normal;}
  button::-moz-focus-inner,input::-moz-focus-inner{padding:0;border:0;}
  button,input[type="button"],input[type="reset"],input[type="submit"]{cursor:pointer;-webkit-appearance:button;}
  input[type="search"]{-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box;-webkit-appearance:textfield;}
  input[type="search"]::-webkit-search-decoration,input[type="search"]::-webkit-search-cancel-button{-webkit-appearance:none;}
  textarea{overflow:auto;vertical-align:top;}
  body{margin:0;font-family: "Helvetica Neue",Helvetica,sans-serif;font-size:15px;line-height:25px;color:#333333;background-color:#ffffff;}
  a{color:#dd4814;text-decoration:none;font-family:'Ubuntu Mono';}
  a:hover{color:#97310e;text-decoration:underline;}
  p{margin:0 0 10px;}
  small{font-size:85%;}
  strong{font-weight:bold;}
  em{font-style:italic;}
  cite{font-style:normal;}

  h1,h2,h3,h4,h5,h6{margin:10px 0;font-family:inherit;font-weight:normal;line-height:1;color:inherit;text-rendering:optimizelegibility;}h1 small,h2 small,h3 small,h4 small,h5 small,h6 small{font-weight:normal;line-height:1;color:#999999;}
  h1{font-size:36px;line-height:40px;}
  h2{font-size:30px;line-height:40px;}
  h3{font-size:24px;line-height:40px;}
  h4{font-size:18px;line-height:20px;}
  h5{font-size:14px;line-height:20px;}
  h6{font-size:12px;line-height:20px;}
  h1 small{font-size:24px;}
  h2 small{font-size:18px;}
  h3 small{font-size:14px;}
  h4 small{font-size:14px;}

  ul,ol{padding:0;margin:0 0 10px 25px;}
  ul ul,ul ol,ol ol,ol ul{margin-bottom:0;}
  li{line-height:20px;}
  ul.unstyled,ol.unstyled{margin-left:0;list-style:none;}
  dl{margin-bottom:20px;}
  dt,dd{line-height:20px;}
  dt{font-weight:bold;}
  dd{margin-left:10px;}
  hr{margin:20px 0;border:0;border-top:1px solid #f5f5f5;border-bottom:1px solid #ffffff;}
  abbr[title]{cursor:help;border-bottom:1px dotted #999999;}
  abbr.initialism{font-size:90%;text-transform:uppercase;}
  blockquote{padding:0 0 0 15px;margin:0 0 20px;border-left:5px solid #f5f5f5;}blockquote p{margin-bottom:0;font-size:16px;font-weight:300;line-height:25px;}
  blockquote small{display:block;line-height:20px;color:#999999;}blockquote small:before{content:'\2014 \00A0';}
  blockquote.pull-right{float:right;padding-right:15px;padding-left:0;border-right:5px solid #f5f5f5;border-left:0;}blockquote.pull-right p,blockquote.pull-right small{text-align:right;}
  blockquote.pull-right small:before{content:'';}
  blockquote.pull-right small:after{content:'\00A0 \2014';}
  q:before,q:after,blockquote:before,blockquote:after{content:"";}
  address{display:block;margin-bottom:20px;font-style:normal;line-height:20px;}
  code,pre{padding:0 3px 2px;font-family:Menlo,Monaco,Consolas,"Courier New",monospace;font-size:12px;color:#333333;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px;}
  code{padding:2px 4px;color:#d14;background-color:#f7f7f9;border:1px solid #e1e1e8;}
  pre{display:block;padding:9.5px;margin:0 0 10px;font-size:13px;line-height:20px;word-break:break-all;word-wrap:break-word;white-space:pre;white-space:pre-wrap;background-color:#f5f5f5;border:1px solid #ccc;border:1px solid rgba(0, 0, 0, 0.15);-webkit-border-radius:4px;-moz-border-radius:4px;border-radius:4px;}pre.prettyprint{margin-bottom:20px;}
  pre code{padding:0;color:inherit;background-color:transparent;border:0;}


  body {
    background-color: #9BA2B0;
  }

  sup {
    font-size: .25em;
    top: -1.5em;
  }
  .container {
    background-color: white;
    width: 1000px;
    margin: 10px auto;
    padding: 30px 20px;
    box-shadow: 0 0 10px 0 rgba(0,0,0,.5);
  }

  hr {
    border-top: 1px solid black;
    border-bottom: 1px solid black;
  }

  .name {
    font-family: 'Roboto Slab', serif;
    font-size: 4em;
    font-weight: 100;
    text-align: center;
    line-height: 60px;
  }

  @media (max-width: 768px){
    .container {
      width: 85%;
      margin: 10px auto;
      padding: 10px 20px;
    }
  }

  /* Use higher contrast and text-weight for printable form. */
  @media print, projection {
       body {
        background-color: white;
      }

      .container {
      background-color: white;
      width: 100%;
      margin: auto auto;
      padding: 0;
      box-shadow: 0;
    }

  }
  </style>
</head>
<body>
  <div class="container">

    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <div style="background-color:red;width:150px;height:150px;"></div>
      </div> <!-- .col -->
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <div style="background-color:red;width:100%;height:50px;color:white;font-size:25px;line-height: 50px;text-align: center;">TENAGA TIMUR FREIGHT (M) SDN BHD</div><br>
          TENAGA TIMUR FREIGHT (M) SDN. BHD.<br>
          (COMPANY NO.: 131190-T)<br>
          10B, LORONG 8/1E, 46050 PETALING JAYA,<br>
          SELANGOR DARUL EHSAN, MALAYSIA.<br>
          TEL: 03-79559433  FAX: 03-79578580<br>
          E-MAIL: ttfrtmy@gmail.com
      </div> <!-- .col -->
    </div> <!-- .row -->


    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div style="border-bottom:2px solid black;"></div>
        <div class="pull-left" contenteditable>
          TENAGA TIMUR FREIGHT (M) SDN. BHD.<br>
          (COMPANY NO.: 131190-T)<br>
          10B, LORONG 8/1E, 46050 PETALING JAYA,<br>
          SELANGOR DARUL EHSAN, MALAYSIA.<br>
          TEL: 03-79559433  FAX: 03-79578580<br>
          E-MAIL: ttfrtmy@gmail.com
        </div>
        <div class="pull-right">
        <div class="" style="font-size:30px;background:black;color:white;padding:10px;">INVOICE</div>
        <div class="" style="font-size:30px;padding:30px 0 0 0;text-align:center;">{{ $invoice->present()->invoiceNumber }}</div>
        </div>

      </div> <!-- .col -->
    </div> <!-- .row -->

    <br>


    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <strong>Job No. :</strong> ( {{ $shipment->present()->fileNumber }} )
      </div> <!-- .col -->
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <div>
          <span class="pull-right clearfix"><strong>Date: </strong> {{ $shipment->present()->fileDate }} </span>
        </div>
      </div> <!-- .col -->
    </div> <!-- .row -->


    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-bordered table-condensed">
          <thead>
            <tr>
              <th class="text-center">ITEM</th>
              <th class="text-center">PARTICULARS</th>
              <th class="text-center">AMOUNT</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td></td>
              <td contenteditable>
                <div>SUBJECT : </div>
                <div>VESSEL : </div>
                <div>FROM/TO : </div>
                <div>B/L NO : </div>
              </td>
              <td></td>
            </tr>
            @for($i = 0; $i < 12; $i++)
            <tr>
              <td contenteditable>&nbsp</td>
              <td contenteditable>&nbsp</td>
              <td contenteditable>&nbsp</td>
            </tr>
            @endfor
          </tbody>

          <tfoot>
            <tr>
              <th></th>
              <th class="text-right">Total</th>
              <th contenteditable></th>
            </tr>
          </tfoot>

        </table>
      </div> <!-- .col -->
    </div> <!-- .row -->


    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">

      </div> <!-- .col -->

      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <br>
        <br>
        <br>
        <br>
        <hr>
        <div class="text-center">TENAGA TIMUR FREIGHT (M) SDN. BHD.</div>
      </div> <!-- .col -->
    </div> <!-- .row -->


  </div>
</body>
</html>

src/app/views/shipments/invoices/show.blade.php
{{{ $invoice }}}