src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get( '/', [
  'as'   => 'home',
  'uses' => 'HomeController@index'
] );

Route::resource( 'sessions', 'SessionsController' );
Route::get( 'logout', [ 'as' => 'logout', 'uses' => 'SessionsController@destroy' ] );

Route::group( array( 'before' => 'csrf|auth' ), function ()
{

  Route::get( 'shipments/{typeAndYear}/{fileNumber}', 'ShipmentsController@showByFileNumber' )
       ->where( 'typeAndYear', '(im|ex|IM|EX)\-[0-9]{2}' )
       ->where( 'fileNumber', '[0-9]{3}' );

  Route::resource( 'shipments', 'ShipmentsController' );
  Route::resource( 'shipments.items', 'ShipmentsItemsController' );
  Route::resource( 'shipments.tasks', 'ShipmentsTasksController' );
  Route::resource( 'shipments.documents', 'ShipmentsDocumentsController' );
  Route::resource( 'shipments.costsheets', 'ShipmentsCostsheetsController' );
  Route::resource( 'shipments.invoices', 'ShipmentsInvoicesController' );
  Route::resource( 'shipments.invoices.items', 'ShipmentsInvoicesItemsController' );

  Route::resource( 'documents', 'DocumentsController' );
  Route::resource( 'ports', 'PortsController' );
  Route::resource( 'vessels', 'VesselsController' );

  Route::resource( 'customers', 'CustomersController' );


  Route::resource( 'users', 'UsersController' );
  Route::resource( 'groups', 'GroupsController' );

  Route::get( 'dashboard', [ 'as' => 'dashboard', function () { return View::make( 'dashboard.index' ); } ] );

  Route::get( 'hrm', function () { return Redirect::route('users.index'); } );
  Route::get( 'crm', function () { return Redirect::route('customers.index'); } );
  Route::get( 'rm', function () { return Redirect::route('documents.index'); } );

  Route::get( 'search', function () { return Redirect::to( 'shipments/' . Input::get('q') ); } );
  Route::get( 'endpoints', function () { return View::make( 'static.endpoints' ); } );
  Route::get( 'help', function () { return View::make( 'static.help' ); } );

} );


Route::get( 'debug', function ()
{

  $shipmentId = 1;
  $invoiceId  = 89;
  Kint::dump(
    JTS\Entities\Shipments\Shipment::findOrFail( $shipmentId )
                                   ->invoices()->findOrFail( $invoiceId )
                                   ->update( [ ] )
  );
  die();
} );

src/app/controllers/VesselsController.php
<?php

use JTS\Entities\Resources\Vessels\VesselRepositoryInterface;
use JTS\Core\Exceptions\ValidationException;

class VesselsController extends \AbstractBaseController {

  /**
   * @var VesselRepositoryInterface
   */
  private $vessel;

  function __construct(VesselRepositoryInterface $vessel)
  {
    $this->vessel = $vessel;
  }

  /**
   * Display a listing of vessels
   *
   * @return Response
   */
  public function index()
  {
    if ( Request::ajax() )
    {
      return $this->vessel->getAllInJson();
    }
    $vessels = $this->vessel->getAll();

    return View::make( 'resources.vessels.index', compact( 'vessels' ) );
  }

  /**
   * Show the form for creating a new vessel
   *
   * @return Response
   */
  public function create()
  {
    return View::make( 'resources.vessels.create' );
  }

  /**
   * Store a newly created vessel in storage.
   *
   * @return Response
   */
  public function store()
  {

    try
    {
      $vessel = $this->vessel->create( Input::all() );
    }
    catch ( ValidationException $e )
    {
      return Redirect::back()->withErrors( $e->getValidator() )->withInput();
    }

    if(Request::ajax())
    {
      return $vessel;
    }

    return Redirect::route( 'resources.vessels.index' );
  }

  /**
   * Display the specified vessel.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function show($id)
  {
    return Redirect::route( 'vessels.edit', [ $id ] );
  }

  /**
   * Show the form for editing the specified vessel.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function edit($id)
  {
    $vessel = $this->vessel->getById( $id );

    return View::make( 'resources.vessels.edit', compact( 'vessel' ) );
  }

  /**
   * Update the specified vessel in storage.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function update($id)
  {
    try
    {
      $this->vessel->update( $id, Input::all() );
    }
    catch ( ValidationException $e )
    {
      return Redirect::back()->withErrors( $e->getValidator() )->withInput();
    }

    return Redirect::route( 'vessels.index' );
  }

  /**
   * Remove the specified vessel from storage.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function destroy($id)
  {
    $this->vessel->destroy( $id );

    return Redirect::route( 'vessels.index' );
  }

  /**
   * Restore the specified vessel from storage.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function restore($id)
  {
    $this->vessel->restore( $id );

    return Redirect::route( 'vessels.index', [ $id ] );
  }

}

src/app/views/resources/vessels/_form.blade.php
<div class="form-group">
  {{ Form::label('name', trans('jts.name'), ['class' => 'col-md-2  control-label'] ) }}
  <div class="col-md-10">
    {{ Form::text('name', null, ['class' => 'form-control'] ) }}
    {{ $errors->first('name', '<span class="help-block">:message</span>') }}
  </div>
</div>

<div class="form-group">
  {{ Form::label('code', trans('jts.code'), ['class' => 'col-md-2  control-label'] ) }}
  <div class="col-md-10">
    {{ Form::text('code', null, ['class' => 'form-control'] ) }}
    {{ $errors->first('code', '<span class="help-block">:message</span>') }}
  </div>
</div>

<div class="form-group">
  {{ Form::label('description', trans('jts.description'), ['class' => 'col-md-2  control-label'] ) }}
  <div class="col-md-10">
    {{ Form::text('description', null, ['class' => 'form-control'] ) }}
    {{ $errors->first('description', '<span class="help-block">:message</span>') }}
  </div>
</div>

src/app/views/resources/vessels/create.blade.php
@extends('layouts.default')

@section('sidebar')
  @include('resources._sidebar')
@stop

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="well">

      {{ Form::open(['route' => 'vessels.store', 'method' => 'post', 'class' => 'form-horizontal']) }}

        <fieldset>
          <legend>{{ trans('jts.creating_new_vessel') }}</legend>

          @include('resources.vessels._form')

          <div class="form-group">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div class="pull-right">
                {{ Form::submit(trans('ui.save'), ['class' => 'btn btn-primary']) }}
              </div>
            </div>
          </div>
        </fieldset>

      {{ Form::close() }}

    </div> <!-- .well -->
  </div> <!-- .col -->
</div> <!-- .row -->
@stop

src/app/views/resources/vessels/edit.blade.php
@extends('layouts.default')

@section('sidebar')
  @include('resources._sidebar')
@stop

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="well">

      {{ Form::model($vessel, ['route' => ['vessels.update', $vessel->id], 'method' => 'put', 'class' => 'form-horizontal']) }}
        <fieldset>

          <legend>{{ trans('jts.editing_vessel') }}</legend>

          @include('resources.vessels._form')

          <div class="form-group">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="pull-right">
                  {{ Form::submit(trans('ui.update'), ['class' => 'btn btn-primary']) }}
                  {{ Form::button(trans('ui.undo_changes'), ['class' => 'btn btn-default', 'type' => 'reset']) }}
                </div>
                <div class="pull-left">
                  <a class="btn btn-danger" href="{{ route('vessels.destroy', $vessel->id ) }}" data-method="delete">{{ trans('ui.delete') }}</a>
                </div>
            </div>
          </div>

        </fieldset>
      {{ Form::close() }}

    </div> <!-- .well -->
  </div> <!-- .col -->
</div> <!-- .row -->

@stop

src/app/views/resources/vessels/index.blade.php
@extends('layouts.default')

@section('sidebar')
  @include('resources._sidebar')
@stop

@section('breadcrumb')
@stop

@section('content')
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <strong class="panel-title">{{ trans('jts.vessels') }}</strong>
    <div class="pull-right">
      <a href="{{ route('vessels.create') }}" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-plus"></i> {{ trans('jts.new_vessel') }}</a>
    </div>
  </div>

  <table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>

      <th>Actions</th>
    </tr>
  </thead>
  <tbody>

    @foreach($vessels as $vessel)
    <tr>
      <td><a href="{{ route('vessels.edit', $vessel->id) }}">{{ $vessel->present()->name }}</a></td>
      <td>
        <a href="{{ route('vessels.edit', $vessel->id) }}" class="btn btn-default btn-xs">Edit</a>
      </td>
    </tr>
    @endforeach


  </tbody>
  </table>

  <div class="panel-footer clearfix">
    <div class="pull-right">
      {{ $vessels->appends(Input::except('page'))->links() }}
    </div>
  </div>
</div>
@stop

src/app/views/resources/vessels/show.blade.php
{{{ $vessel }}}